### ISSUE TITLE
No refresh on d.ts files modifications

### ISSUE THREAD

**Issue by vjau** [mologie/meteor-typescript#3]
Hi, 
after trying out your package, i have tried to write d.ts files for my app's packages. 
The problem is that when i modify those d.ts files, meteor won't catch the changes. I have to kill Meteor and relaunch it.
Thank you in advance for your help.

Regards

**Comment by vjau** [comment]
Is this still developed ?

**Comment by mologie** [comment]
Hey vjau, I'm so sorry for missing your ticket. I did not touch this repository for quite some time because things are working nicely here. I have received your ticket via email, but it got lost under a pile of other mail. Sorry :(.

This plugin is still being developed. I use it in a production application without any issues so far. But please keep in mind that this is experimental software. There are no tests, and things may break at any time with TypeScript or Meteor changes.

I can confirm your issue and will dig into Meteor to figure out how to convince it to trigger a rebuild even though ".d.ts" files are not processed by this plugin later today.

Cheers, Oliver

**Comment by vjau** [comment]
Thank you Oliver, i didn't want it to sound like "when will it be fixed ?!?", i was wondering is this package was still active. 
Thank you for your work on this.

Cya

Vincent

**Comment by vjau** [comment]
It works, thanks !
